// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhzzdfzjqtbbknwelitx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoenpkZnpqcXRiYmtud2VsaXR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Mjc3NjgsImV4cCI6MjA3MTIwMzc2OH0.g6IdsByGyqRjWt3g7JGIH9sPtuNm2z4A3Iv8x_sZ5eA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});